### ISSUE TITLE
Album artwork thumbnail is sometimes wrong

### ISSUE THREAD

**Issue by hawkeye0203** [citruspi/Spotify-Notifications#10]
It seems random when it happens, but the album artwork that shows on the notification bubble will sometimes be of the last song or another song from the past.

**Comment by bawigga** [comment]
I just came here to report this bug. It's happened twice in a row for me. Running version 0.4.8 from homebrew cask.

![screenshot 2015-02-08 14 35 06](https://cloud.githubusercontent.com/assets/7358/6098300/f15fad8a-af9f-11e4-8818-cdba50bdd5f0.png)

Here's the expected Artwork: 
![screenshot 2015-02-08 14 37 58](https://cloud.githubusercontent.com/assets/7358/6098318/2e9b3bd8-afa0-11e4-9069-21d93cf452cf.png)

**Comment by citruspi** [comment]
@bawigga,

This issue was resolved in version 0.5.0 which was released on October 27, 2014.

Unfortunately, I haven't released a signed binary since 0.4.8 which is why the website and Homebrew Cask both present 0.4.8.

If you'd like to update you could use [the link I provided](http://cl.ly/0g1S3V1T3W0l) above to @hawkeye0203. However, the link is for a beta release of 0.5.0 which just fixed that issue.

If you'd like a more recent version, I'd recommend building the 0.5.X branch which contains version 0.5.1.

Sorry for any inconvenience.

&mdash; @citruspi

**Comment by citruspi** [comment]
@bawigga @hawkeye0203 ,

I just wanted to give you an update. Yesterday I signed and published binaries for versions [0.5.0](https://github.com/citruspi/Spotify-Notifications/releases/tag/0.5.0) and [0.5.1](https://github.com/citruspi/Spotify-Notifications/releases/tag/0.5.1), feel free to download the latest version.

&mdash; @citruspi

**Comment by bawigga** [comment]
@citruspi Thanks! Just installed from brew cask!
