### ISSUE TITLE
Updated icons based on Spotify's redesign

### ISSUE THREAD

**Issue by randybruder** [citruspi/Spotify-Notifications#48]
Here's updated assets for Spotify-Notifications, based on the Spotify redesign. Included are:
```
AppIcon.icns
icon.icns
status_bar_colour.tiff
```

https://dl.dropboxusercontent.com/u/8895/spotify-notifications-icons.zip

Here's what it looks like with the proper icons:
![image](https://cloud.githubusercontent.com/assets/6447487/8923305/e1e1f12c-34bc-11e5-8ade-ef84ff1b48ef.png)

**Comment by swrobel** [comment]
:+1:

**Comment by drewcovi** [comment]
@randybruder could you PR that thing? or create a fork?

**Comment by randybruder** [comment]
@drewcovi I don't see how, the three files mentioned in the original post aren't in the Github project, just the compiled release. Don't know how to PR/fork it if the files aren't there for me to replace.

**Comment by robinnorth** [comment]
@randybruder Check the `0.5.X` branch (https://github.com/citruspi/Spotify-Notifications/tree/0.5.X), the status bar assets are under `Spotify Notifications` and the app icons are under `Spotify Notications/Images.xcassets/AppIcon.appiconset`.

**Comment by evansimoni** [comment]
+1 for this PR

**Comment by randybruder** [comment]
Ok, made a PR. No idea if I did it right.

https://github.com/citruspi/Spotify-Notifications/pull/54

**Comment by drewcovi** [comment]
@randybruder  I think you did it right, but the images are the old green not the new green.

**Comment by randybruder** [comment]
Ok, think I did it right this time.

https://github.com/citruspi/Spotify-Notifications/pull/55

**Comment by drewcovi** [comment]
dy-no-mite! well done on what I'm guessing is a first PR! For future reference, you can always continue to commit to an open PR, no need to close and create anew!

**Comment by randybruder** [comment]
Well, first two now. It was the different branches thing that was tripping me up, I didn't realize forking a repo would also fork all the branches too. Thanks for your help.

**Comment by evansimoni** [comment]
Rad! Does anyone know how to update the application file on the main website?

**Comment by randybruder** [comment]
That would involve compiling the code (probably updating the version to 0.5.2) and having @citruspi update the main website.

**Comment by citruspi** [comment]
> That would involve compiling the code (probably updating the version to 0.5.2) and having @citruspi update the main website.

Correct. Sorry about dropping the ball on this, it's been on my todo list but it just kept getting postponed.

I'll need to do a couple things to get the pull request shipped. I'd like to accomplish these today, but I'm going to provide a checklist so that the status of the issue is a little more transparent.

- [ ] Review the changes
- [ ] Bump the version and update the Change Log
- [ ] Merge the changes in
- [ ] Build and `codesign` an archive for users
- [ ] Tag the release and upload the archive
- [ ] Update the link on the site
- [ ] Update the [recipe][recipe] for [Homebrew Cask][brewcask]

I'll update this pull request as I make progress towards it.

Also, big thanks to @randybruder for the pull request and congrats on the first (two) pull request(s)! :tada: 

[recipe]: https://github.com/caskroom/homebrew-cask/blob/master/Casks/spotify-notifications.rb
[brewcask]: http://caskroom.io

**Comment by citruspi** [comment]
Okay, so its been merged, archived, signed, tagged, and released. The website has been updated.

I've submitted a pull request to Homebrew Cask for the new version - caskroom/homebrew-cask#14276.

I think once that's merged in we're good to go.

**Comment by randybruder** [comment]
Hot damn

**Comment by drewcovi** [comment]
:+1

**Comment by drewcovi** [comment]
+1

**Comment by citruspi** [comment]
Well, [it's official](https://github.com/caskroom/homebrew-cask/pull/14276). :cake:

**Comment by robinnorth** [comment]
Nice one! :tada:

**Comment by evansimoni** [comment]
This is great, thanks @citruspi @randybruder !
:clap:
