### ISSUE TITLE
Disable Spotify logo in notification

### ISSUE THREAD

**Issue by brycedorn** [citruspi/Spotify-Notifications#58]
Thanks so much for this! Really missed the little notification of what song was next ever since Growl stopped working :crying_cat_face: glad to have it back.

One thing that I miss though - is there any way to disable the Spotify logo in the notification and replace it with the album art? Like so:

<img width="233" alt="screen shot 2015-12-15 at 12 19 20 pm" src="https://cloud.githubusercontent.com/assets/3171252/11819588/517b07c6-a326-11e5-84ca-9942700efd63.png">

& sorry if this was already asked, only read through the current issues.

**Comment by citruspi** [comment]
Does the album art not show up for you at all? Because both the Spotify icon and the album artwork should appear in the notification if you're using OS X 10.9 or later.

![](https://cloud.githubusercontent.com/assets/2125849/11821569/3c6ba89c-a338-11e5-855c-03922997a41b.png)

Inclusion of the album artwork should be enabled by default, but you can check what it's set to in the settings.

![untitled 4](https://cloud.githubusercontent.com/assets/2125849/11821655/a19c462c-a338-11e5-8e13-f05058c171b7.png)

If the album art is showing up for you, but you just want to see it on the left side, that should come with #56.

**Comment by brycedorn** [comment]
album art is showing fine - just meant the logo on the left. looks like that pr addresses this though, thanks!

**Comment by citruspi** [comment]
No worries. I'll leave this issue open until that gets merged.

**Comment by sebj** [comment]
#56 has been merged @brycedorn! 😃
