### ISSUE TITLE
Homebrew Cask still on v0.5.2

### ISSUE THREAD

**Issue by underyx** [citruspi/Spotify-Notifications#80]
Seems to be missing now, so homebrew cask is still installing the old version.

**Comment by citruspi** [comment]
It's not just that the archive is missing from GitHub, but that [the cask][0] hasn't been updated to the new version.

The `version`, `sha256`, `url`, and `appcast` values will need to be updated. I can submit a PR to the `homebrew-cask` repository sometime today or tomorrow.

[0]: https://github.com/caskroom/homebrew-cask/blob/60531a2812005dd5f17dc92f3ce7419af3c5d019/Casks/spotify-notifications.rb

**Comment by underyx** [comment]
Well my line of thinking was, if you just upload the archive, the caskroom maintainers will soon update the cask cause the new version will show up on the appcast feed.

**Comment by citruspi** [comment]
I'm no longer hosting the archives on GitHub, they're now hosted on https://downloads.spotify-notifications.citruspi.io.

To be frank, I'm not a fan of GitHub as a product or as a company and I don't _personally_ use them - I have a private GitLab instance which I run for personal stuff. The only reason that this (and other repositories of mine) exist on GitHub are because the community is here - moving the repository would increase the friction involved to contribute a pull request or submit an issue. 

For this reason, I'd like to limit the use of GitHub to features which require community involvement (e.g. pull requests and issue tracking) while avoiding the use of other features like archive hosting for releases and GitHub Pages.

**Comment by citruspi** [comment]
I've submitted a pull request updating the cask version to 0.6.0, I'll close this issue once that is merged in.

**Comment by citruspi** [comment]
Homebrew Cask now points to the v0.6.0 build of Spotify Notifications.
